// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPteHjZc-XF-XhI0AqdKnX1KHRPGdcUCU',
    appId: '1:1078341541114:web:efa6cd3c60886f51d37d43',
    messagingSenderId: '1078341541114',
    projectId: 'flutter3-55001',
    authDomain: 'flutter3-55001.firebaseapp.com',
    storageBucket: 'flutter3-55001.appspot.com',
    measurementId: 'G-V8Z1YDVJZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcLfLd3r12T2zyLWzlMbaH2qb1uuMISw',
    appId: '1:1078341541114:android:9a7f30520fceb8f2d37d43',
    messagingSenderId: '1078341541114',
    projectId: 'flutter3-55001',
    storageBucket: 'flutter3-55001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjJ1h-iRov8ojb2CT70rynmNEl0vmJYM',
    appId: '1:1078341541114:ios:98dfcc3e61ad9f95d37d43',
    messagingSenderId: '1078341541114',
    projectId: 'flutter3-55001',
    storageBucket: 'flutter3-55001.appspot.com',
    iosClientId: '1078341541114-47kfhjv9cugb1n2k68690on3lm7chbjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjJ1h-iRov8ojb2CT70rynmNEl0vmJYM',
    appId: '1:1078341541114:ios:98dfcc3e61ad9f95d37d43',
    messagingSenderId: '1078341541114',
    projectId: 'flutter3-55001',
    storageBucket: 'flutter3-55001.appspot.com',
    iosClientId: '1078341541114-47kfhjv9cugb1n2k68690on3lm7chbjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase3',
  );
}
